# Generated by Django 5.2.8 on 2025-11-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
